project: 
  type: website
  output-dir: docs

website: 
  title: Podstawy Programowania
  sidebar:
    style: "docked" 
    contents:
      - index.qmd
      - section : "Wykłady"
        contents:
          - lectures/wyklad1.md
          - lectures/wyklad2.md
          - lectures/wyklad3.qmd
          - lectures/wyklad4.qmd
          - lectures/wyklad5.qmd
          - lectures/wyklad6.qmd
          - lectures/wyklad7.qmd
  navbar:
    left:
          - href: ksiazki.qmd
            text: Książki
          

format:
  html:
    theme: cosmo
    css: style.css
    toc: true
    self-contained-math: true